server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:usmanovaziz/market-place-config.git
          default-label: master
          search-paths: marketplace-config
