spring:
  config:
    activate:
      on-profile: default

  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/

management:
  endpoints:
    web:
      exposure:
        include: "*"
