spring:
  config:
    activate:
      on-profile: default
  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      tls:
        enabled: false
