spring:
  application:
    name: user-service

  cloud:
    config:
      enabled: true
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true      

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      properties:
        batch:
          size: 16384
        linger:
          ms: 5
        compression:
          type: snappy
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/learn_grafana?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

  sql:
    init:
      mode: embedded

  jpa:
    hibernate:
      ddl-auto: update
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    open-in-view: false

  data:
    redis:
      repositories:
        enabled: false
      database: 0
      host: localhost
      port: 6379
      timeout: 60000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    session:
      timeout: 30m
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 40MB

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 69b13063cd48d4
    password: a8ceb0e36e8366
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    session:
      timeout: 30m

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
        